import os
from typing import Annotated
from dotenv import load_dotenv
from fastapi import HTTPException, UploadFile, status, APIRouter
from pydantic import Field
from app.schemas import CategorySchemaInEnum, GptScheamOut, UploadFileSchemaOut, RemoveNamespaceSchemaOut
from app.agent_logic import upload_file_logic, remove_namespace, agent_response
load_dotenv()


router = APIRouter(prefix="/api/v1")


POSTGRES_USER = os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD = os.getenv("POSTGRES_PASSWORD")
POSTGRES_HOST = os.getenv("POSTGRES_HOST")
POSTGRES_PORT = os.getenv("POSTGRES_PORT")
POSTGRES_DB = os.getenv("POSTGRES_DB")

DB_URI = f'postgresql://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DB}'


@router.post(
    "/upload",
    response_model=UploadFileSchemaOut,
    status_code=status.HTTP_201_CREATED,
)
async def upload_file(
    user_file: UploadFile,
    category: Annotated[
        CategorySchemaInEnum,
        Field(
            description="the name of the category of the uploaded data", max_length=50
        ),
    ],
) -> UploadFileSchemaOut:
    """
    Upload a file and assign it to a specific category.

    This endpoint accepts a file and a category name, processes the upload using
    the `upload_file_logic` function, and returns metadata about the uploaded file.

    Args:
        user_file (UploadFile): The file to be uploaded.
        category (str): The category under which the file should be stored. Maximum length is 50 characters.

    Returns:
        UploadFileSchemaOut: Schema containing information about the uploaded file, such as file name, URL, and category.

    Raises:
        HTTPException: If the upload fails due to a known HTTP error.
        HTTPException (500): If an unexpected error occurs during the upload process.
    """
    try:
        result = await upload_file_logic(user_file=user_file, category=category)
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occured: {str(e)}",
        )


@router.delete(
    "/delete-namespace",
    response_model=RemoveNamespaceSchemaOut,
    status_code=status.HTTP_200_OK,
)
async def remove_namespace_from_index(
    category: Annotated[
        str,
        Field(
            description="the name of the category you want to remove", max_length=50
        ),
    ],
) -> RemoveNamespaceSchemaOut:
    """
    Remove a namespace (category) from an index.

    This endpoint deletes a specific namespace or category from the system by
    calling the `remove_namespace` function. It returns a response confirming
    the deletion result.

    Args:
        category (str): The name of the category (namespace) to remove. Maximum length is 50 characters.

    Returns:
        RemoveNamespaceSchemaOut: Schema containing information about the deletion,
        including success status and any relevant messages.

    Raises:
        HTTPException: If the deletion fails due to a known HTTP error.
        HTTPException (500): If an unexpected error occurs during the deletion process.
    """
    try:
        result = await remove_namespace(namespace=category)
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occured: {str(e)}",
        )


@router.post(
    "/agent-response",
    # response_model=GptScheamOut,
    status_code=status.HTTP_200_OK,
)
async def get_response_from_agent(
    question: Annotated[
        str,
        Field(description="question to be asked to the agent", max_length=100),
    ],

):
    """
    Receive a question from the user and return a response generated by the agent.

    This endpoint sends the provided question to the agent, which uses its tools, context,
    and recent conversation history (if applicable) to generate a relevant and concise answer.

    Args:
        question (str): The question text to be asked to the agent. Maximum length is 100 characters.

    Returns:
        GptScheamOut: The structured response from the agent containing the answer and any metadata.

    Raises:
        HTTPException:
            - Status 500 if any unexpected error occurs during agent processing.
            - Re-raises any existing HTTPException encountered during processing.
    """
    try:
        result = await agent_response(question=question)
        return result
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occured: {str(e)}",
        )

    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"An error occured: {str(e)}",
        )
