from enum import Enum
from pydantic import BaseModel, Field
from typing import Annotated


class GptScheamOut(BaseModel):
    answer: Annotated[str, Field(
        description='the answer generated by chatgpt')]


class UploadFileSchemaOut(BaseModel):
    success: Annotated[str, Field(
        description='Response from uploading a file')]


class RemoveIndexSchemaOut(BaseModel):
    response: Annotated[str, Field(
        description='Response from removing index.')]


class RemoveNamespaceSchemaOut(BaseModel):
    response: Annotated[str, Field(
        description='Response from removing index.')]


class CategorySchemaInEnum(str, Enum):
    cars = 'cars'
    addeesses = 'addresses'
